name:                spreading-power
version:             0.1.0.0
github:              "chrisbloecker/spreading-power"
license:             BSD3
author:              "Christopher Blöcker"
maintainer:          "mail@chrisbloecker.se"
copyright:           "2022 Christopher Blöcker"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/spreading-power#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - containers
  - megaparsec
  - mtl
  - parallel
  - random
  - text

executables:
  spreading-power-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O3
    dependencies:
    - containers
    - megaparsec
    - mtl
    - optparse-applicative
    - random
    - spreading-power
    - text

tests:
  spreading-power-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - spreading-power
